# This is a basic workflow to help you get started with Actions

name: release


on:

  push:
    tags:
    - '*'


jobs:
  new_release:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install jq
        run: sudo apt-get install -y jq


      - name: Add ticket
        run: sh ./scripts/release.sh
        env:
          TOKEN: ${{secrets.TOKEN_AUTH}}
          ORG_ID: ${{secrets.ORG_ID}}

      - name: Do test
        run: sh ./scripts/test.sh
        env:
          TOKEN: ${{secrets.TOKEN_AUTH}}
          ORG_ID: ${{secrets.ORG_ID}}


