# This is a basic workflow to help you get started with Actions

name: release


on:

  push:
    tags:
    - '*'


jobs:
  new_release:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v2

      - name: install jq
      run: sudo apt-get install -y jq


      - name: add ticket
        run: sh ./scripts/release.sh
        env:
          TOKEN: ${{secrets.TOKEN_AUTH}}
          ORG_ID: ${{secrets.ORG_ID}}

